services:
  api-transactions:
    container_name: api-transactions
    image: api-transactions
    hostname: api-transactions
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - ./:/src
    restart: "unless-stopped"
    command: npm start
